### ISSUE TITLE
[FEAT] 법정동 코드 관리

### ISSUE THREAD

**Issue by jamie9504** [woowacourse-teams/2020-welcome-korea#122]
**Subject**
법정동 코드 관리

**Detail**
- 관리 데이터 추출
[법정동분류_By제이미.xlsx](https://github.com/woowacourse-teams/2020-legeno-around-here/files/5046826/_By.xlsx)
    - 모든지 4Depth로 분류할 수 있다는 것을 알 수 있음

- 어떻게 관리하면 좋을지 논의했던 부분
1. 일단 외부 API (주소 조회) 연동이 시간이 없으니 내부 DB에 넣어놓고 활용하도록 ✅ 
2. 저장시 한 컬럼 VS 5개의 나뉜 컬럼
    - 일단 한 컬럼으로 하고 like를 거는 것은 어떤지
    - 여러 컬럼으로 해도 좋을 듯 한데 (JPA에서 자동 쿼리 기능 이용)?
        - 이렇게 되면 어려우려나?

- 제안 사항
   - 일단 객체는 하나로 가도 될 것 같아요! (EX - AREA) : DB TABLE도 1개요! - 관리 용이
    - 법정동 분류를 4Depth로 나눌 수 있으니, 컬럼으로 각각 저장해두는 건 어떨까요?
       > 모두 4depth로 분리되니, String으로 관리하는 것과 개발시 큰 차이가 나지 않습니다. (어떤 건 3depth고 어떤건 2depth일 걱정 X)
        - Column : (ex) 1depthName, 2depthName, 3depthName, 4depthName
            - 이름 추천 좀 해주세요!
            - 이럴경우 JPA 메서드명으로 자동 생성하는 쿼리를 이용해서 질의 가능할 것으로 판단되서 이 방법이 String보다 좋지 않을까 싶은데 어떠신가요!
               - `findAllBy1depthName(String 1depthName)`
               - `findAllBy1depthNameAnd2depthName(String 1depthName, String 2depthName)`
            - 이렇게 저장을 하게 되면, 원하는 Area (ex : 서울시로만도 가능, 서울시 송파구로도 가능)를 글 쓸 때나, 기본 지역으로 저장하는 데는 문제가 되지 않을 것 같아요.
    - 저장할 부분 > 법정동 코드를 굳이 저장할 필요가 있을지는 고민, 그래도 저장해놓으면 좋을까요 ?ㅁ?
        - 세부 법정동 코드의 경우(나눠놓은 것) 저장할 필요가 있을까요? 저장할 필요가 있다면, Embeddable 객체(코드 + 명)로 묶어도 되겠네요.
    - 고민 부분 : 객체지향 관점에서 null을 허용하는 것이 괜찮을지, 아니면 empty로 저장해두는 것이 괜찮을지
        - 저장 공간상은 null이 더 유리하...ㄹ것 같긴 하지만 (확실하지 않고) 고민이에요!

- 구조 생각한 부문
    - User는 Area를 참조한다. N:1 (기본 지역) / Area는 User를 참조할 필요가 없다. N:1 
    - Post는 Area를 참조한다. N:1 (기본 지역) / Area는 Post를 참조할 필요가 있을 것 같기도 - 수상 이력.. 아니면 이건 그냥 쿼리로.. 일단 없다.
    - 조회시 Get 메서드의 파라미터로 1depthName, 2depthName, 3depthName, 4depthName을 받는다.
        - Null 가능, 단 하위 뎁스의 이름이 있는 경우 상위 뎁스도 존재해야만 함

- 법정동의 경우 DB에 직접 데이터를 밀어 넣는다면 R만, 
  Java 서비스를 통해 데이터를 밀어 넣는다면 C + R만 개발하면 될 것 같아요.

**Reference**
- https://www.code.go.kr/stdcode/regCodeL.do 에서 다운로드 가능
- 다운로드 자료(2020.08.09(일) 기준 존재하는 법정동 Data) : [법정동_20200809.xlsx](https://github.com/woowacourse-teams/2020-legeno-around-here/files/5046811/_20200809.xlsx)

**Comment by aegis1920** [comment]
이 부분 라흐랑 잠깐 이야기 했었는데요! 검색을 통해서 주소를 찾는다면 여러 개의 칼럼으로 나눌 필요 없이 하나의 컬럼(String)으로 관리해도 괜찮을 것 같다고 생각했습니다. 2번의 첫 번째처럼 한 컬럼으로 두고 like를 거는 거죠. 물론 구조적으로는 여러 칼럼으로 나누는 게 낫겠지만 지금 상황에서는 하나의 컬럼으로 가는 게 여러모로 생산적이지 않을까 생각합니다 :)

**Comment by jamie9504** [comment]
결론) 일단 Full Name과 나눈 4개 Name, 그리고 사용여부까지 이렇게 저장하도록

- FullName : 사용자 검색시 용이 with Like
- 나눈 Name : 수상이력 산정시 용이 with 필드 검색...

- 사용 여부 : 혹시나 추후에 법정동 변경시, 사용하지 않을 경우를 대비하여 1, 0으로 저장
- null 대신 empty (null은 equals 비교가 어려우므로..)

CSV 파일을 만들어봤습니다. _CSV 파일은 업로드가 안되어 부득이하게 압축했어요_
[area.csv.zip](https://github.com/woowacourse-teams/2020-legeno-around-here/files/5051340/area.csv.zip)

**Comment by jamie9504** [comment]
Mock 데이터 설정

- 현재 일단 h2로 구성되어 있기 때문에, Real/Test 각각 서울시 이하 주소(총 493건)로 Mock 데이터를 넣어둔 상태입니다.
    - Mock 데이터를 넣어둔 이유) 지역의 경우 R(조회) 기능만 있기 때문
- http://localhost:8080/areas로 토큰 넣어서 조회하면 아래와 같이 조회되오니 작업시 참고하시기 바랍니다.
``` json
{
"content": [
  {
"fullName": "서울특별시",
"firstDepthName": "서울특별시",
"secondDepthName": "",
"thirdDepthName": "",
"fourthDepthName": ""
},
  {
"fullName": "서울특별시 종로구",
"firstDepthName": "서울특별시",
"secondDepthName": "종로구",
"thirdDepthName": "",
"fourthDepthName": ""
},
  {
"fullName": "서울특별시 종로구 청운동",
"firstDepthName": "서울특별시",
"secondDepthName": "종로구",
"thirdDepthName": "청운동",
"fourthDepthName": ""
},
  {
"fullName": "서울특별시 종로구 신교동",
"firstDepthName": "서울특별시",
"secondDepthName": "종로구",
"thirdDepthName": "신교동",
"fourthDepthName": ""
},
  {
"fullName": "서울특별시 종로구 궁정동",
"firstDepthName": "서울특별시",
"secondDepthName": "종로구",
"thirdDepthName": "궁정동",
"fourthDepthName": ""
},
  {
"fullName": "서울특별시 종로구 효자동",
"firstDepthName": "서울특별시",
"secondDepthName": "종로구",
"thirdDepthName": "효자동",
"fourthDepthName": ""
},
  {
"fullName": "서울특별시 종로구 창성동",
"firstDepthName": "서울특별시",
"secondDepthName": "종로구",
"thirdDepthName": "창성동",
"fourthDepthName": ""
},
  {
"fullName": "서울특별시 종로구 통의동",
"firstDepthName": "서울특별시",
"secondDepthName": "종로구",
"thirdDepthName": "통의동",
"fourthDepthName": ""
},
  {
"fullName": "서울특별시 종로구 적선동",
"firstDepthName": "서울특별시",
"secondDepthName": "종로구",
"thirdDepthName": "적선동",
"fourthDepthName": ""
},
  {
"fullName": "서울특별시 종로구 통인동",
"firstDepthName": "서울특별시",
"secondDepthName": "종로구",
"thirdDepthName": "통인동",
"fourthDepthName": ""
}
],
"pageable": {
"sort": {
"sorted": true,
"unsorted": false,
"empty": false
},
"offset": 0,
"pageNumber": 0,
"pageSize": 10,
"paged": true,
"unpaged": false
},
"totalPages": 50,
"totalElements": 493,
"last": false,
"size": 10,
"numberOfElements": 10,
"number": 0,
"sort": {
"sorted": true,
"unsorted": false,
"empty": false
},
"first": true,
"empty": false
}
```
