### ISSUE TITLE
[DOCS] PULL-REQUEST-TEMPLATE 수정

### ISSUE THREAD

**Issue by ttkmw** [woowacourse-teams/2020-welcome-korea#33]
**Subject**
풀 리퀘스트 템플릿

**Detail**
현재 이슈 템플릿은 등록되어 있지만, 풀리퀘스트 템플릿은 등록되어 있지 않습니다. 풀 리퀘스트 템플릿을 등록하는 이슈입니다. 템플릿의 내용은 원하시는 이슈 담당자가 제안해주시면 좋을 것 같습니다. 내용 작성 시, 아래 example을 참고해주시는 것도 좋을 것 같습니다.

**Reference**
how-to-guide: https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository
example: 
1. https://embeddedartistry.com/blog/2017/08/04/a-github-pull-request-template-for-your-projects/
2. https://github.com/DE-labtory/it-chain/blob/develop/.github/PULL_REQUEST_TEMPLATE.md

etc:
https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

**Comment by aegis1920** [comment]
작업중입니다 :)
