### ISSUE TITLE
[FEAT] Area 도메인 정의

### ISSUE THREAD

**Issue by aegis1920** [woowacourse-teams/2020-welcome-korea#39]
**Subject**
Area 도메인 정의

**Detail**
- 2020/07/15
    1. Area는 3 depth까지 관리 (like 당근마켓)
    2. 지역 조회는 외부 API(행정안전부, 카카오맵... etc) 사용 논의 필요
    3. 관리하는 지역(예 - 시/군/구)의 경우 각각 다른 필드로 관리하는 것이 좋음
        - 이유 : 한 필드로 관리하게 되면 검색시마다 해당 데이터를 나누는 작업을 해야하기 때문
    4. 글 조회시(랭크/최신글) 글이 하나라도 있는 지역만 조회되면 사용자 측면에서 좋을 것
        - 그렇기 위해서는 SelectBox 식으로 조회가 되는 것이 좋다고 생각함 - 추후 협의
        - 3단(depth별) SelectBox적용시, 상위 선택한 조건에 맞추어 다음 조회할 영역 데이터를 정리하여 보여주도록 할 것
            - 예) 서울특별시 선택시 서울의 구만 조회
            - 예) 서울특별시 송파구 선택시 송파구의 동들만 조회
    5. 글 등록시는 전체 지역이 조회되어야 함
    - 도메인 이해가 어려울 것으로 판단, 추후 협의하여 담당자 지정할 것

**Reference**
write here

**Comment by ttkmw** [comment]
작업중입니다.

**Comment by ihoph** [comment]
완료했습니다.
