### ISSUE TITLE
[FEAT] 사용자를 위한 alert 추가

### ISSUE THREAD

**Issue by yelimkim98** [woowacourse-teams/2020-welcome-korea#398]
**Subject**
꼭 필요한 alert 추가

**detail**
1. 로그인 실패 alert
2. 회원가입 시 이메일 중복 alert
3. 부문 신청 완료 alert

**Reference**
write here

**Comment by Hamliet** [comment]
로그인 성공, 실패
메일 중복 확인, 실패
메일 인증 성공, 실패
부문 신청 성공, 실패
