### ISSUE TITLE
[BUG] 특정 이미지 업로드 불가

### ISSUE THREAD

**Issue by Hamliet** [woowacourse-teams/2020-welcome-korea#411]
**Where**
1. 특정 이미지 업로드 불가

**Bug detail**
1. 작은 용량의 이미지만 올라가는 문제
2. 1MB 이상은 이미지 업로드 불가

**Fix plan**
1. 용량별로 이미지 테스트 후 버그 수정

**Comment by jamie9504** [comment]
nginx에서 기본 허용 사이즈를 초과하여 차단하였기 때문에 기본 사이즈를 100M로 변경하는 설정 추가했음

```
  client_max_body_size 100M;

```

참고 블로그 [LINK](https://m.blog.naver.com/PostView.nhn?blogId=doogle&logNo=220595916156&proxyReferer=https:%2F%2Fwww.google.com%2F)
