### ISSUE TITLE
[BUG] 조금씩 가로스크롤이 생기는 문제

### ISSUE THREAD

**Issue by yelimkim98** [woowacourse-teams/2020-welcome-korea#457]
**Where**
조금씩 가로스크롤이 생기는 문제

**Bug detail**
기분나쁘게 조금씩 가로스크롤이 있습니다...

좌우 슬라이드를 사용할때도 이 가로스크롤 때문에 불편합니다.
슬라이드 사용할때가 아니더라도 뭔가 거슬립니다.

**Fix plan**

**Comment by jamie9504** [comment]
#### 글 상세
- 전체 가로 스크롤
<img src="https://user-images.githubusercontent.com/59511689/94099886-f6441e00-fe66-11ea-944c-7ce65a43f7b4.png" width="300">

#### 홈 화면
- 홈 아이템창에 가로/세로 스크롤 생김
<img src="https://user-images.githubusercontent.com/59511689/94100028-6357b380-fe67-11ea-8810-302174eeaa7f.png" width="300">
