### ISSUE TITLE
[REFACTOR] 네이밍 PopularityPostCreatorAward VS PopularPostAward

### ISSUE THREAD

**Issue by yelimkim98** [woowacourse-teams/2020-welcome-korea#504]
**Subject**
네이밍 PopularityPostCreatorAward VS PopularPostAward

**Detail**
PopularityPostCreatorAward
PopularityPostCreatorAwardService
PopularityPostCreatorAwardRepository
등등... 인기 글 작성자 상 시리즈의 이름이 불편합니다..!

이름이 너무 길고, PopularPostAward 라고만 써도 뜻을 잘 알아볼 수 있다고 생각합니다.

그래서 제가 인기글 수상 기능을 구현하면서
Service 이름을 PopularPostAwardService 로 했는데,
PopularityPostCreatorAward 엔티티와 PopularityPostCreatorAwardRepository 까지 이름을 바꾸자니

테이블 이름이 바뀌고.. 구조가 바뀌고...
이런 연쇄적인 문제가 생길 것 같아서
바꾸지 않고 이슈만 생성해놓고 갑니다!

**Comment by jamie9504** [comment]
PopularPostAward로 회의 후 변경되어 Close 합니다.
