### ISSUE TITLE
[FEAT] 부문 관련 필요 기능 정의

### ISSUE THREAD

**Issue by Hamliet** [woowacourse-teams/2020-welcome-korea#81]
**Subject**
부문 관련 필요 기능 회의

**Detail**
부문 관련 필요 기능이 무엇인지 정의합니다.
![image](https://user-images.githubusercontent.com/59511689/89164156-af961e00-d5b1-11ea-8f53-80089d8a544c.png)

- 회원
    - [x] 부문 승인 요청(C') ⭕
    - [x] 등록된 부문 전체 조회(R), 단 건 조회(R) ⭕
    - [x] 본인이 등록한 부문 전체 조회(R) ❓
    - [x] 본인이 승인 요청한 부문 전체 조회(R), 단 건 조회(R) ❓
    - [ ] 승인 요청된 전체 부문 조회(R), 단 건 조회(R) ❓ 
- Admin 필요 기능(회원 기능 외 고유 필요 기능)
    - [x] 부문 등록(C), 수정(U), 삭제(D) ⭕
    - [x] 부문 승인(U) ⭕ 

- 부문 name은 unique하게 갈 것인가?
   - 부문 상태에 무관한 unique / 부문 상태와 연관된 unique

**Comment by jamie9504** [comment]
부문 등록 진행합니다.
